samples ={
'ggH_4photons':{'dataset':'local:./local_samples/ggHTo4gamma.root',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[]},
'DoubleEG_2017B':{'dataset':'/DoubleEG/Run2017B-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2017'},
'DoubleEG_2017C':{'dataset':'/DoubleEG/Run2017C-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2017'},
'DoubleEG_2017D':{'dataset':'/DoubleEG/Run2017D-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2017'},
'DoubleEG_2017E':{'dataset':'/DoubleEG/Run2017E-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2017'},
'DoubleEG_2017F':{'dataset':'/DoubleEG/Run2017F-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2017'},
'EGamma_2018A':{'dataset':'/EGamma/Run2018A-UL2018_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2018'},
'EGamma_2018B':{'dataset':'/EGamma/Run2018B-UL2018_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2018'},
'EGamma_2018C':{'dataset':'/EGamma/Run2018C-UL2018_MiniAODv2_NanoAODv9-v1/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2018'},
'EGamma_2018D':{'dataset':'/EGamma/Run2018D-UL2018_MiniAODv2_NanoAODv9-v3/NANOAOD',
                    'triggers':['HLT_TriplePhoton_20_20_20_CaloIdLV2'],
                    'veto_triggers':[],
                    'era': '2018'},
'EGamma_2022C_v2':{'dataset':'/EGamma/Run2022C-PromptNanoAODv10-v2/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2022'},
'EGamma_2022C_v1-v1':{'dataset':'/EGamma/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2022'},
'EGamma_2022D_v1-v1':{'dataset':'/EGamma/Run2022D-PromptNanoAODv10_v1-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2022'},
'EGamma_2022D_v2-v1':{'dataset':'/EGamma/Run2022D-PromptNanoAODv10_v2-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2022'},
'EGamma_2022E_v1-v2':{'dataset':'/EGamma/Run2022E-PromptNanoAODv10_v1-v2/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2022'},
'EGamma_2022F_v1-v2':{'dataset':'/EGamma/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2022'},
'EGamma_2022G_v1-v1':{'dataset':'/EGamma/Run2022G-PromptNanoAODv10_v1-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2022'},
'EGamma0_2023B_v1-v1':{'dataset':'/EGamma0/Run2023B-PromptNanoAODv11p9_v1-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'},                                                                                                                                            
'EGamma1_2023B_v1-v1':{'dataset':'/EGamma1/Run2023B-PromptNanoAODv11p9_v1-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'},                                                                                                                                            
'EGamma0_2023C_v1-v1':{'dataset':'/EGamma0/Run2023C-PromptNanoAODv11p9_v1-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'},                                                                                                                                            
'EGamma1_2023C_v1-v1':{'dataset':'/EGamma1/Run2023C-PromptNanoAODv11p9_v1-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'},                                                                                                                                            
'EGamma0_2023C_v3-v1':{'dataset':'/EGamma0/Run2023C-PromptNanoAODv12_v3-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'},                                                                                                                                            
'EGamma1_2023C_v3-v1':{'dataset':'/EGamma1/Run2023C-PromptNanoAODv12_v3-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'},                                                                                                                                            
'EGamma0_2023C_v4-v1':{'dataset':'/EGamma0/Run2023C-PromptNanoAODv12_v4-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'},                                                                                                                                            
'EGamma1_2023C_v4-v1':{'dataset':'/EGamma1/Run2023C-PromptNanoAODv12_v4-v1/NANOAOD',
                    'triggers':['HLT_DoublePhoton33_CaloIdL'],
                    'veto_triggers':[],
                    'era': '2023'}
}